<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_div classHB1eCd-X3SwIb-haAclfdiv classH_4a36eb</name>
   <tag></tag>
   <elementGuidId>2bbc82d8-84b1-4231-ab7c-48b7dfaae523</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.Uc2NEf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22fc9ae9-1869-4db4-987e-3220df1bcfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Uc2NEf</value>
      <webElementGuid>639b5c88-e723-429d-9c77-c07e0cf39df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;div class=&quot;HB1eCd-X3SwIb-haAclf&quot;>&lt;div class=&quot;HB1eCd-X3SwIb-i8xkGf&quot;>&lt;div class=&quot;tk3N6e-cXJiPb tk3N6e-cXJiPb-TSZdd tk3N6e-cXJiPb-GMvhG&quot;>Не удалось открыть файл, поскольку в вашем браузере отключено использование JavaScript. Включите его и перезагрузите страницу.&lt;/div>&lt;/div>&lt;br>&lt;/div>QA test assignmentHello dear aspirant!Your test assignment is to fill in this form using Katalon Studio. Then upload this Katalon project to the github. Make sure your Katalon script set the right link in the latest question of the form.IMPORTANT: your Katalon script must not click on Submit/Send. Please do this manually and only once when you're done.Good luck! :)   vor.arkadiy@gmail.com (без совместного доступа) Сменить аккаунт   Черновик сохранен.* ОбязательноName *Мой ответEmail *Мой ответSomeday I will learn  *drawingplaying musica new languagea new sport activitytax codeLink to your public GitHub repository with Katalon project which opens and fills in this form *Мой ответОтправитьОчистить формуНикогда не используйте формы Google для передачи паролей.Форма создана в домене Altermeliora OU. Сообщение о нарушении Формы  </value>
      <webElementGuid>132484d8-27be-4f60-97d4-86fba9e94cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;HB1eCd-UMrnmb&quot;]/body[@class=&quot;D8bnZd&quot;]/div[@class=&quot;Uc2NEf&quot;]</value>
      <webElementGuid>364bfa31-ec15-49e5-9f2c-89af94412f4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>2c5aa836-06c1-4c57-a7b8-bf965855ef63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;&lt;div class=&quot;HB1eCd-X3SwIb-haAclf&quot;>&lt;div class=&quot;HB1eCd-X3SwIb-i8xkGf&quot;>&lt;div class=&quot;tk3N6e-cXJiPb tk3N6e-cXJiPb-TSZdd tk3N6e-cXJiPb-GMvhG&quot;>Не удалось открыть файл, поскольку в вашем браузере отключено использование JavaScript. Включите его и перезагрузите страницу.&lt;/div>&lt;/div>&lt;br>&lt;/div>QA test assignmentHello dear aspirant!Your test assignment is to fill in this form using Katalon Studio. Then upload this Katalon project to the github. Make sure your Katalon script set the right link in the latest question of the form.IMPORTANT: your Katalon script must not click on Submit/Send. Please do this manually and only once when you&quot; , &quot;'&quot; , &quot;re done.Good luck! :)   vor.arkadiy@gmail.com (без совместного доступа) Сменить аккаунт   Черновик сохранен.* ОбязательноName *Мой ответEmail *Мой ответSomeday I will learn  *drawingplaying musica new languagea new sport activitytax codeLink to your public GitHub repository with Katalon project which opens and fills in this form *Мой ответОтправитьОчистить формуНикогда не используйте формы Google для передачи паролей.Форма создана в домене Altermeliora OU. Сообщение о нарушении Формы  &quot;) or . = concat(&quot;&lt;div class=&quot;HB1eCd-X3SwIb-haAclf&quot;>&lt;div class=&quot;HB1eCd-X3SwIb-i8xkGf&quot;>&lt;div class=&quot;tk3N6e-cXJiPb tk3N6e-cXJiPb-TSZdd tk3N6e-cXJiPb-GMvhG&quot;>Не удалось открыть файл, поскольку в вашем браузере отключено использование JavaScript. Включите его и перезагрузите страницу.&lt;/div>&lt;/div>&lt;br>&lt;/div>QA test assignmentHello dear aspirant!Your test assignment is to fill in this form using Katalon Studio. Then upload this Katalon project to the github. Make sure your Katalon script set the right link in the latest question of the form.IMPORTANT: your Katalon script must not click on Submit/Send. Please do this manually and only once when you&quot; , &quot;'&quot; , &quot;re done.Good luck! :)   vor.arkadiy@gmail.com (без совместного доступа) Сменить аккаунт   Черновик сохранен.* ОбязательноName *Мой ответEmail *Мой ответSomeday I will learn  *drawingplaying musica new languagea new sport activitytax codeLink to your public GitHub repository with Katalon project which opens and fills in this form *Мой ответОтправитьОчистить формуНикогда не используйте формы Google для передачи паролей.Форма создана в домене Altermeliora OU. Сообщение о нарушении Формы  &quot;))]</value>
      <webElementGuid>bf717eca-9365-4dff-9a09-8b1e72811057</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
